name: colorfilter_generator
description: Collection of ColorFilter matrices that can be used with ColorFiltered and generator to create custom color filters.
version: 0.0.6
homepage: https://ensorta.com

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  matrix2d: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
